### PR TITLE
Graphics for new ui and app market

### PR DESCRIPTION
**Pull request by neynah**

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @neynah ! This seems fine; I can merge it right now so long as you can answer these questions, so I don't end up in a copyright mess.
- Is this your original work?
- What license are you willing to distribute it under?

It seems this pull request doesn't indicate what changes I need to make for my sandstorm-pkgdef.capnp. I guess the idea is that it isn't needed yet, and I can do this separately. It's helpful if you can indicate what action you want me to take as part of the pull request.

Cheers and thanks,

Asheesh.

**Comment by paulproteus** [comment]
Hi! I now see https://github.com/paulproteus/meteor-todos-sandstorm/issues/1 -- it's helpful if you can reference issues from the pull request, since I just didn't see my emails in the order you might have expected.

I don't know if there are higher-res icons. I imagine there aren't, but I can ask upstream, but I'd kind of rather not since I don't think they care about us very much. I hope that isn't too annoying; by all means, feel free to tell me it's worth asking.

Hope that helps,

Asheesh.

**Comment by paulproteus** [comment]
I'm also a little confused -- are you submitting a pull request proposing creating two copies of the same file, in this repo? I would be -1 on making duplicate copies, and +1 on a symbolic link if needed.

But I'm not sure why it would be needed. I imagine I could adjust my `sandstorm-pkgdef.capnp` file to point at the existing paths, rather than adding copies. So let me know.

**Comment by neynah** [comment]
Oh dear. Sorry, I should have been more clear. 

I'll be sure to reference the issues. I forgot how many things you have going on!

These graphics already exist in the repo, however in png form. The mini icon and the launcher also have rounded corners. The launcher has a drop shadow, and the larger icon is as is. These are nice touches but not totally essential if you don't think it's a good idea to use slightly modified graphics. Although, SVG will make it easier to scale for larger resolutions since we're allowing people to submit 24, 48, 128, 256, 150, 300.

I haven't made any changes to the design itself, just its presentation if that makes sense. So it's not my own work as I found the source material in this repo (I assume the author has permissions to use the graphic).

**Comment by paulproteus** [comment]
Hi @neynah ! I'm just getting to this now; apologies that it took so long.

**Comment by neynah** [comment]
No problem! :)

**Comment by paulproteus** [comment]
In case it's useful feedback, here are some things that would have made
this pull request easier for me to deal with:

In the pull request, make sure there is a description.

Make sure the description contains information about the origin of the
files you're submitting.

Since per https://docs.sandstorm.io/en/latest/developing/publishing-apps/
the different icons have different technical names, specifically appGrid
grain market marketBig, mention those technical names rather than the image
sizes. Bonus points if you submit filenames that contain these technical
names, so I have even less to remember.

If possible, your pull request could include changes to
sandstorm-pkgdef.capnp. That would make my life ~500% easier when reviewing
a pull request like this. If you want I can help make sure you know how to
do that.

Use a title that either clearly relates to the project you're submitting a
pull request to, or clearly indicates what other project it is referring
to. With the title of "Graphics for new ui and app market" I originally
thought that you were proposing a new UI for meteor-todos itself.

http://chris.beams.io/posts/git-commit/ is a web page that talks about good
git commit messages. Commit messages aren't always important in one's own
projects, but since they become part of the pull request, writing good ones
when you expect other people to consume your commits is an indication that
you care about your work being easy to merge.

Hope that helps. Always happy to discuss more but wanted to write all this
before I forget it all.

**Comment by neynah** [comment]
Thanks for the feedback. Especially helpful as everyone else has just merged everything without mentioning anything. I'll keep these in mind for the future. :)

**Pull request merged**
